# Generated by Django 4.2.6 on 2024-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='dislikesCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='likesCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
