# Generated by Django 4.2.6 on 2024-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_user_age_user_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
